#!/usr/bin/env bash
#
# Generated by Claude Code, refer the header of SETUP_ENV.md.
#
# Set up a local Python environment for developing SGLang from this checkout.
#
# The environment is built from the pyproject in the repo's `python/` package
# directory -- this script lives outside it. SGLang ships
# one pyproject per hardware platform (pyproject.toml is the CUDA one,
# pyproject_other.toml covers MPS/ROCm/HPU/MUSA, plus _cpu / _npu / _xpu), and
# setup.py only ever reads `python/pyproject.toml`. This script picks the right
# file for the current machine, swaps it in for the duration of the install,
# and restores the checkout afterwards so `git status` stays clean.
#
# See SETUP_ENV.md (same directory) for the long-form documentation.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# The installable package and every pyproject variant live in <repo>/python,
# which is NOT this script's directory -- resolve them from the repo root.
PYTHON_DIR="${REPO_ROOT}/python"

PYTHON_VERSION="3.12"
VENV_DIR="${REPO_ROOT}/.venv"
VARIANT="auto"
EXTRAS=""
BUILD_RUST="auto" # auto | none
WRITE_VSCODE=1
RECREATE=0
DRY_RUN=0

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die() {
  printf '\033[1;31merror:\033[0m %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: studyIterations/setup_env.sh [options]

Creates a virtualenv and installs sglang into it as an editable install,
using the pyproject that matches this machine.

Options:
  --variant <name>   auto (default), cuda, mps, cpu, hip, npu, xpu, empty
                     'empty' = pure-Python subset, no torch (works anywhere).
  --python <ver>     Python version for the venv (default: 3.12).
  --venv <path>      Venv location (default: <repo>/.venv).
  --extras <list>    Comma-separated extras, overrides the per-variant default
                     (e.g. dev_mps, "all,dev", or "" for none).
  --no-rust          Skip building the Rust extension modules
                     (sets SGLANG_BUILD_RUST_EXTS=none). Needed if you have no
                     Rust toolchain; the extensions are optional at runtime.
  --no-vscode        Do not write .vscode/settings.json.
  --recreate         Delete and recreate the venv if it already exists.
  --dry-run          Resolve dependencies without installing anything.
  -h, --help         Show this help.

Examples:
  studyIterations/setup_env.sh                      # auto-detect platform
  studyIterations/setup_env.sh --extras dev_mps     # macOS + test dependencies
  studyIterations/setup_env.sh --variant empty      # lightweight, torch-free
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  --variant)
    VARIANT="${2:?--variant needs a value}"
    shift 2
    ;;
  --python)
    PYTHON_VERSION="${2:?--python needs a value}"
    shift 2
    ;;
  --venv)
    VENV_DIR="${2:?--venv needs a value}"
    shift 2
    ;;
  --extras)
    EXTRAS="${2-}"
    EXTRAS_SET=1
    shift 2
    ;;
  --no-rust)
    BUILD_RUST="none"
    shift
    ;;
  --no-vscode)
    WRITE_VSCODE=0
    shift
    ;;
  --recreate)
    RECREATE=1
    shift
    ;;
  --dry-run)
    DRY_RUN=1
    shift
    ;;
  -h | --help)
    usage
    exit 0
    ;;
  *) die "unknown option: $1 (see --help)" ;;
  esac
done

# --- 1. Pick the platform variant -------------------------------------------

detect_variant() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"
  case "${os}" in
  Darwin)
    [[ "${arch}" == "arm64" ]] ||
      die "macOS on ${arch} has no supported build; re-run with --variant empty"
    echo "mps"
    ;;
  Linux)
    if command -v nvidia-smi >/dev/null 2>&1; then
      echo "cuda"
    elif command -v rocminfo >/dev/null 2>&1 || [[ -d /opt/rocm ]]; then
      echo "hip"
    elif command -v npu-smi >/dev/null 2>&1; then
      echo "npu"
    else
      echo "cpu"
    fi
    ;;
  *) die "unsupported OS '${os}'; re-run with an explicit --variant" ;;
  esac
}

if [[ "${VARIANT}" == "auto" ]]; then
  VARIANT="$(detect_variant)"
  log "Detected platform variant: ${VARIANT}"
fi

# Each variant maps to a pyproject file and a default extras set.
case "${VARIANT}" in
cuda)
  PYPROJECT_SRC="pyproject.toml"
  DEFAULT_EXTRAS="all"
  ;;
mps)
  PYPROJECT_SRC="pyproject_other.toml"
  DEFAULT_EXTRAS="all_mps"
  ;;
hip)
  PYPROJECT_SRC="pyproject_other.toml"
  DEFAULT_EXTRAS="all_hip"
  ;;
empty)
  PYPROJECT_SRC="pyproject_other.toml"
  DEFAULT_EXTRAS="srt_empty"
  ;;
cpu)
  PYPROJECT_SRC="pyproject_cpu.toml"
  DEFAULT_EXTRAS="dev"
  ;;
npu)
  PYPROJECT_SRC="pyproject_npu.toml"
  DEFAULT_EXTRAS="all_npu"
  ;;
xpu)
  PYPROJECT_SRC="pyproject_xpu.toml"
  DEFAULT_EXTRAS="all"
  ;;
*) die "unknown variant '${VARIANT}' (see --help)" ;;
esac

[[ -f "${PYTHON_DIR}/${PYPROJECT_SRC}" ]] || die "missing ${PYTHON_DIR}/${PYPROJECT_SRC}"
# --extras (including `--extras ""`) wins over the per-variant default.
[[ -n "${EXTRAS_SET-}" ]] || EXTRAS="${DEFAULT_EXTRAS}"

if [[ -n "${EXTRAS}" ]]; then
  TARGET="${PYTHON_DIR}[${EXTRAS}]"
else
  TARGET="${PYTHON_DIR}"
fi

# --- 2. Rust extension modules ----------------------------------------------

# setup.py discovers PyO3 extension crates in ../rust via `cargo metadata`, so
# the install needs a Rust toolchain unless we opt out. They are optional at
# runtime (only the inkling multimodal processor and the Rust server use them).
if [[ "${BUILD_RUST}" == "auto" ]] && ! command -v cargo >/dev/null 2>&1; then
  warn "cargo not found — building without Rust extension modules"
  BUILD_RUST="none"
fi
if [[ "${BUILD_RUST}" == "none" ]]; then
  export SGLANG_BUILD_RUST_EXTS=none
fi

# --- 3. Create the virtualenv ------------------------------------------------

HAVE_UV=0
command -v uv >/dev/null 2>&1 && HAVE_UV=1

if [[ "${RECREATE}" -eq 1 && -d "${VENV_DIR}" ]]; then
  log "Removing existing venv ${VENV_DIR}"
  rm -rf "${VENV_DIR}"
fi

VENV_PY="${VENV_DIR}/bin/python"
if [[ -x "${VENV_PY}" ]]; then
  log "Reusing existing venv ${VENV_DIR} ($(${VENV_PY} --version))"
elif [[ "${HAVE_UV}" -eq 1 ]]; then
  log "Creating venv ${VENV_DIR} (Python ${PYTHON_VERSION}, via uv)"
  uv venv --python "${PYTHON_VERSION}" --seed "${VENV_DIR}"
else
  # No uv: fall back to an interpreter of the requested version on PATH.
  BASE_PY="$(command -v "python${PYTHON_VERSION}" || true)"
  [[ -n "${BASE_PY}" ]] || die "python${PYTHON_VERSION} not on PATH; install it, or install uv (https://docs.astral.sh/uv/)"
  log "Creating venv ${VENV_DIR} (${BASE_PY}, via venv)"
  "${BASE_PY}" -m venv "${VENV_DIR}"
  "${VENV_PY}" -m pip install --quiet --upgrade pip setuptools wheel
fi

# --- 4. Swap in the platform pyproject, install, then restore ----------------

PYPROJECT="${PYTHON_DIR}/pyproject.toml"
BACKUP=""
restore_pyproject() {
  if [[ -n "${BACKUP}" && -f "${BACKUP}" ]]; then
    cp "${BACKUP}" "${PYPROJECT}"
    rm -f "${BACKUP}"
    BACKUP=""
    log "Restored python/pyproject.toml"
  fi
}
trap restore_pyproject EXIT INT TERM

if [[ "${PYPROJECT_SRC}" != "pyproject.toml" ]]; then
  BACKUP="$(mktemp "${TMPDIR:-/tmp}/sglang-pyproject.XXXXXX")"
  cp "${PYPROJECT}" "${BACKUP}"
  cp "${PYTHON_DIR}/${PYPROJECT_SRC}" "${PYPROJECT}"
  log "Using ${PYPROJECT_SRC} as python/pyproject.toml for this install"
fi

log "Installing editable: sglang[${EXTRAS}] (variant=${VARIANT}, rust=${BUILD_RUST})"
INSTALL_FLAGS=()
[[ "${DRY_RUN}" -eq 1 ]] && INSTALL_FLAGS+=(--dry-run)
# `${arr[@]+...}` keeps an empty array from tripping `set -u` on bash 3.2.
if [[ "${HAVE_UV}" -eq 1 ]]; then
  uv pip install --python "${VENV_PY}" ${INSTALL_FLAGS[@]+"${INSTALL_FLAGS[@]}"} -e "${TARGET}"
else
  "${VENV_PY}" -m pip install ${INSTALL_FLAGS[@]+"${INSTALL_FLAGS[@]}"} -e "${TARGET}"
fi

restore_pyproject
trap - EXIT INT TERM

if [[ "${DRY_RUN}" -eq 1 ]]; then
  log "Dry run complete — nothing was installed."
  exit 0
fi

# --- 5. Point VS Code at the venv --------------------------------------------

if [[ "${WRITE_VSCODE}" -eq 1 ]]; then
  VSCODE_DIR="${REPO_ROOT}/.vscode"
  VSCODE_SETTINGS="${VSCODE_DIR}/settings.json"
  REL_VENV="${VENV_DIR#"${REPO_ROOT}/"}"
  if [[ -e "${VSCODE_SETTINGS}" ]]; then
    warn "${VSCODE_SETTINGS} exists — leaving it alone; set python.defaultInterpreterPath to ${VENV_PY}"
  else
    mkdir -p "${VSCODE_DIR}"
    cat >"${VSCODE_SETTINGS}" <<EOF
{
  "python.defaultInterpreterPath": "\${workspaceFolder}/${REL_VENV}/bin/python",
  "python.terminal.activateEnvironment": true,
  "python.analysis.extraPaths": ["\${workspaceFolder}/python"],
  "python.testing.pytestEnabled": true
}
EOF
    log "Wrote ${VSCODE_SETTINGS} (.vscode is gitignored)"
  fi
fi

# --- 6. Smoke test ------------------------------------------------------------

log "Importing sglang (this pulls in torch, may take a few seconds)"
if "${VENV_PY}" -c 'import sglang; print("sglang", sglang.__version__)'; then
  log "Environment ready."
else
  warn "sglang installed but failed to import — see the traceback above"
fi

cat <<EOF

Interpreter : ${VENV_PY}
Activate    : source ${VENV_DIR}/bin/activate
VS Code     : Cmd+Shift+P > "Python: Select Interpreter" > ${VENV_PY}
Docs        : studyIterations/SETUP_ENV.md
EOF
